//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicResXFileCodeGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchEngine.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;instrumentation&quot;: {
        ///        &quot;pingUrlBase&quot;: &quot;https://www.bingapis.com/api/ping?IG=E86668D804C149438DFC0972CE52C9E3&amp;CID=070910FF0C0362112C11188E0DD06323&amp;ID=&quot;,
        ///        &quot;pageLoadPingUrl&quot;: &quot;https://www.bingapis.com/api/ping/pageload&quot;
        ///    },
        ///    &quot;webPages&quot;: {
        ///        &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=bill+gates&quot;,
        ///        &quot;webSearchUrlPingSuffix&quot;: &quot;DevEx,5425.1&quot;,
        ///        &quot;totalEstimatedMatches&quot;: 14100000,
        ///        &quot;value&quot;: [
        ///            {
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BingTestJson {
            get {
                return ResourceManager.GetString("BingTestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchEngineDatabase.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocp-Apim-Subscription-Key.
        /// </summary>
        public static string OcpApimSubscriptionKey {
            get {
                return ResourceManager.GetString("OcpApimSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PlusSymbol {
            get {
                return ResourceManager.GetString("PlusSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchEngine.
        /// </summary>
        public static string SearchEngine {
            get {
                return ResourceManager.GetString("SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchEngine.Business.Engines.{0}Engine.
        /// </summary>
        public static string SearchEngineBusinessEngines {
            get {
                return ResourceManager.GetString("SearchEngineBusinessEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string WhiteSpaceSymbol {
            get {
                return ResourceManager.GetString("WhiteSpaceSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;yandexsearch version=&quot;1.0&quot;&gt;
        ///    &lt;request&gt;
        ///        &lt;query&gt;Казанский Кремль&lt;/query&gt;
        ///        &lt;page&gt;0&lt;/page&gt;
        ///        &lt;sortby order=&quot;descending&quot; priority=&quot;no&quot;&gt;rlv&lt;/sortby&gt;
        ///        &lt;maxpassages/&gt;
        ///        &lt;groupings&gt;
        ///            &lt;groupby attr=&quot;d&quot; mode=&quot;deep&quot; groups-on-page=&quot;10&quot; docs-in-group=&quot;1&quot; curcateg=&quot;-1&quot;/&gt;
        ///        &lt;/groupings&gt;
        ///    &lt;/request&gt;
        ///    &lt;response date=&quot;20200116T160853&quot;&gt;
        ///        &lt;reqid&gt;1579190933543349-9193804179513602050792-vla1-3759-XML&lt;/reqid&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YandexTestXml {
            get {
                return ResourceManager.GetString("YandexTestXml", resourceCulture);
            }
        }
    }
}
