//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicResXFileCodeGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchEngine.Resources.TestStringResources", typeof(TestStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevExpress MVC5 TreeView.
        /// </summary>
        public static string BingDevExpressMVC5TreeViewQuery {
            get {
                return ResourceManager.GetString("BingDevExpressMVC5TreeViewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;instrumentation&quot;: {
        ///        &quot;pingUrlBase&quot;: &quot;https://www.bingapis.com/api/ping?IG=E86668D804C149438DFC0972CE52C9E3&amp;CID=070910FF0C0362112C11188E0DD06323&amp;ID=&quot;,
        ///        &quot;pageLoadPingUrl&quot;: &quot;https://www.bingapis.com/api/ping/pageload&quot;
        ///    },
        ///    &quot;webPages&quot;: {
        ///        &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=bill+gates&quot;,
        ///        &quot;webSearchUrlPingSuffix&quot;: &quot;DevEx,5425.1&quot;,
        ///        &quot;totalEstimatedMatches&quot;: 14100000,
        ///        &quot;value&quot;: [
        ///            {
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BingDevExpressMVC5TreeViewTestJson {
            get {
                return ResourceManager.GetString("BingDevExpressMVC5TreeViewTestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.cognitive.microsoft.com/bing/v7.0/search?q=DevExpress%2BMVC5%2BTreeView.
        /// </summary>
        public static string BingDevExpressMVC5TreeViewTestRequest {
            get {
                return ResourceManager.GetString("BingDevExpressMVC5TreeViewTestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;instrumentation&quot;: {
        ///        &quot;pingUrlBase&quot;: &quot;https://www.bingapis.com/api/ping?IG=E86668D804C149438DFC0972CE52C9E3&amp;CID=070910FF0C0362112C11188E0DD06323&amp;ID=&quot;,
        ///        &quot;pageLoadPingUrl&quot;: &quot;https://www.bingapis.com/api/ping/pageload&quot;
        ///    },
        ///    &quot;webPages&quot;: {
        ///        &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=bill+gates&quot;,
        ///        &quot;webSearchUrlPingSuffix&quot;: &quot;DevEx,5425.1&quot;,
        ///        &quot;totalEstimatedMatches&quot;: 14100000,
        ///        &quot;value&quot;: [
        ///            {
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BingTestJson {
            get {
                return ResourceManager.GetString("BingTestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire State Building.
        /// </summary>
        public static string GoogleEmpireStateBuildingQuery {
            get {
                return ResourceManager.GetString("GoogleEmpireStateBuildingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;kind&quot;: &quot;customsearch#search&quot;,
        ///    &quot;url&quot;: {
        ///        &quot;type&quot;: &quot;application/json&quot;,
        ///        &quot;template&quot;: &quot;https://www.googleapis.com/customsearch/v1?q={searchTerms}&amp;num={count?}&amp;start={startIndex?}&amp;lr={language?}&amp;safe={safe?}&amp;cx={cx?}&amp;sort={sort?}&amp;filter={filter?}&amp;gl={gl?}&amp;cr={cr?}&amp;googlehost={googleHost?}&amp;c2coff={disableCnTwTranslation?}&amp;hq={hq?}&amp;hl={hl?}&amp;siteSearch={siteSearch?}&amp;siteSearchFilter={siteSearchFilter?}&amp;exactTerms={exactTerms?}&amp;excludeTerms={excludeTerms?}&amp;linkSite={linkSite?}&amp;orTerms={or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoogleEmpireStateBuildingTestJson {
            get {
                return ResourceManager.GetString("GoogleEmpireStateBuildingTestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/customsearch/v1?key=AIzaSyDjIxUEe6flD99KChSJ3248Lc_4E_FbtCo&amp;q=Empire%2BState%2BBuilding&amp;cx=008892241395134864135:cu97aeslmrd&amp;num=10.
        /// </summary>
        public static string GoogleEmpireStateBuildingTestRequest {
            get {
                return ResourceManager.GetString("GoogleEmpireStateBuildingTestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;kind&quot;: &quot;customsearch#search&quot;,
        ///    &quot;url&quot;: {
        ///        &quot;type&quot;: &quot;application/json&quot;,
        ///        &quot;template&quot;: &quot;https://www.googleapis.com/customsearch/v1?q={searchTerms}&amp;num={count?}&amp;start={startIndex?}&amp;lr={language?}&amp;safe={safe?}&amp;cx={cx?}&amp;sort={sort?}&amp;filter={filter?}&amp;gl={gl?}&amp;cr={cr?}&amp;googlehost={googleHost?}&amp;c2coff={disableCnTwTranslation?}&amp;hq={hq?}&amp;hl={hl?}&amp;siteSearch={siteSearch?}&amp;siteSearchFilter={siteSearchFilter?}&amp;exactTerms={exactTerms?}&amp;excludeTerms={excludeTerms?}&amp;linkSite={linkSite?}&amp;orTerms={or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoogleTestJson {
            get {
                return ResourceManager.GetString("GoogleTestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саммит большой восьмерки.
        /// </summary>
        public static string YandexGroupOfEightQuery {
            get {
                return ResourceManager.GetString("YandexGroupOfEightQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yandex.com/search/xml?l10n=en&amp;user=maxim-okulin&amp;key=03.271131870:3cd406dd968f16a13abeb89e0af29889&amp;query=%D0%A1%D0%B0%D0%BC%D0%BC%D0%B8%D1%82%2B%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9%2B%D0%B2%D0%BE%D1%81%D1%8C%D0%BC%D0%B5%D1%80%D0%BA%D0%B8.
        /// </summary>
        public static string YandexGroupOfEightTestRequest {
            get {
                return ResourceManager.GetString("YandexGroupOfEightTestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;yandexsearch version=&quot;1.0&quot;&gt;
        ///    &lt;request&gt;
        ///        &lt;query&gt;Саммит+большой+восьмерки&lt;/query&gt;
        ///        &lt;page&gt;0&lt;/page&gt;
        ///        &lt;sortby order=&quot;descending&quot; priority=&quot;no&quot;&gt;rlv&lt;/sortby&gt;
        ///        &lt;maxpassages/&gt;
        ///        &lt;groupings&gt;
        ///            &lt;groupby attr=&quot;d&quot; mode=&quot;deep&quot; groups-on-page=&quot;10&quot; docs-in-group=&quot;1&quot; curcateg=&quot;-1&quot;/&gt;
        ///        &lt;/groupings&gt;
        ///    &lt;/request&gt;
        ///    &lt;response date=&quot;20200123T054531&quot;&gt;
        ///        &lt;reqid&gt;1579758330882735-197355654245704367360050-man1-3562-XML&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YandexGroupOfEightTestXml {
            get {
                return ResourceManager.GetString("YandexGroupOfEightTestXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;yandexsearch version=&quot;1.0&quot;&gt;
        ///    &lt;request&gt;
        ///        &lt;query&gt;Казанский Кремль&lt;/query&gt;
        ///        &lt;page&gt;0&lt;/page&gt;
        ///        &lt;sortby order=&quot;descending&quot; priority=&quot;no&quot;&gt;rlv&lt;/sortby&gt;
        ///        &lt;maxpassages/&gt;
        ///        &lt;groupings&gt;
        ///            &lt;groupby attr=&quot;d&quot; mode=&quot;deep&quot; groups-on-page=&quot;10&quot; docs-in-group=&quot;1&quot; curcateg=&quot;-1&quot;/&gt;
        ///        &lt;/groupings&gt;
        ///    &lt;/request&gt;
        ///    &lt;response date=&quot;20200116T160853&quot;&gt;
        ///        &lt;reqid&gt;1579190933543349-9193804179513602050792-vla1-3759-XML&lt;/reqid&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YandexTestXml {
            get {
                return ResourceManager.GetString("YandexTestXml", resourceCulture);
            }
        }
    }
}
